#!/bin/sh
#
# While testing we need to create test-accounts and add them to
# the dao.ts file to simulate: a GUARDIAN-address, and a
# DAO-address. Such addresses are of the form test-account-*.
# This hook makes sure we don't commit such modifications

test_lines=$(grep $1 -e 'test-account-')

if ! [ -z "$test_lines" ]
then
  echo >&2 "You forgot to delete the test addresses from dao.ts"
  echo >&2 "> $test_lines"
  exit 1
fi

exit 0