#!/bin/sh
#
# While testing we need to comment a line in external.ts
# so we can immediatelly call "withdraw_all_external"
# This hook makes sure we don't commit the commented line

commented=$(grep $1 -e '//.*assert(context.epochHeight >= withdraw_epoch, "Not enough time has passed")')
uncommented=$(grep $1 -e 'assert(context.epochHeight >= withdraw_epoch, "Not enough time has passed")')

if ! [ -z "$commented" ]
then
  echo >&2 "You forgot to uncomment the assert in withdraw_external"
  echo >&2 "$commented"
  exit 1
fi

if [ -z "$uncommented" ]
then
  echo >&2 "The assert in withdraw_external changed? Update this hook please"
  exit 1
fi

exit 0